import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const alegreyaBold = localFont({
  src: "../assets/fonts/Alegreya-Bold.ttf",
  variable: "--font-Alegreya-Bold",
});

const openSansRegular = localFont({
  src: "../assets/fonts/OpenSans-Regular.ttf",
  variable: "--font-OpenSans-Regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${alegreyaBold.variable} ${openSansRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
